[build]
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NETLIFY_IDENTITY_URL = "https://digskills.netlify.app/.netlify/identity"
